% Copyright (C) 2015-2026 Tristan Schmidlechner, Vittorio Stumpo,
% Bas van Niftrik, and Jorn Fierstra
% ASTRAN Lab, Department of Neurosurgery, University Hospital Zurich
% SPDX-License-Identifier: BSD-3-Clause
%
function configurations = sensitivity_configurations()
%SENSITIVITY_CONFIGURATIONS Parameter grid used in the 20-control analysis.

configurations = table( ...
    [10;5;20;10;10;10;10], [90;95;80;90;90;90;90], ...
    [6;6;6;6;6;4;8], [12;12;12;8;16;12;12], ...
    {'baseline';'threshold_5_95';'threshold_20_80';'temporal_8'; ...
     'temporal_16';'spatial_4mm';'spatial_8mm'}, ...
    'VariableNames',{'lower_percent','upper_percent','spatial_fwhm_mm', ...
    'temporal_window_volumes','name'});
end
